services:
  mysql:
    image: mysql:8.0
    container_name: socialmeli-mysql
    environment:
      MYSQL_DATABASE: meli_social
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: